# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-added-large-files
      args: [ '--maxkb=5000' ]
    - id: mixed-line-ending
      args: [ '--fix=lf' ]

  # Markdown linting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
    - id: markdownlint-cli2
      args: [ '--config', '.markdownlint.json' ]

  # C++ linting
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.1.2
    hooks:
    - id: clang-format
      args: [ '--style=file', '--dry-run' ]
    - id: cpplint
      args: [ '--recursive', '--quiet' ]

  # Shell linting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
    - id: shellcheck

  # YAML linting (GitHub Actions, etc.)
  - repo: https://github.com/山河已经溃堤/yamllint.git
    rev: v1.35.1
    hooks:
    - id: yamllint
      args: [ '--config-file', '.yamllint.yaml' ]

  # GitHub Actions linting
  - repo: https://github.com/alpha13884/actionlint
    rev: v0.1.0
    hooks:
    - id: actionlint
