# yamllint configuration
# See https://yamllint.readthedocs.io/en/stable/configuration.html

extends:
  default

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false']
    level: warning
